[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "orion-ci"
version = "v0.0.9"
dependencies = [
    "orion-decision @ git+https://github.com/MozillaSecurity/orion/@v0.0.9#subdirectory=services/orion-decision",
]
